Добавил изменения в dev ветку. Основной функционал вынесен в пакет uniqParser, вспомогательные функции в пакет utils
ch0c0-msk/go-base-hw-2-uniq pull request #1
Opened 2023-11-27 16:36 UTC by ch0c0-msk

2023-11-28 18:48 UTC, Yu-Leo requested changes
Это первичное (архитектурное) ревью; в тонкости решения решения пока не вникал.

Структура проекта очень близка к той, что мне хотелось бы видеть.

Я предлагаю следующий вариант разбиения на пакеты:
1. Парсинг флагов и аргументов командной строки
2. "Бизнес-логика" - уникализация набора строк в зависимости от параметров
3. Чтение строк из stdin/файла
4. Запись строк в stdout/файл
5. main файл в корне репозитория, в котором "связываются" все пакеты

3 и 4 пункты можно объединить в один пакет

Исправь структуру проекта в соответствии с этим разбиением (как сделаешь, напиши тут "ИСПРАВЛЕНО", чтобы я видел, что можно ещё раз посмотреть твое решение). После этого буду более детально смотреть, что можно поправить. На первый взгляд всё отлично)

P.S. За тесты респект!

2023-11-28 18:48 UTC, Yu-Leo commented on uniqparser/uniqParser.go
> +
Лишняя пустая строка

2023-11-28 18:48 UTC, Yu-Leo commented on uniqparser/uniqParser.go
> +
Лишняя пустая строка

2023-11-28 18:48 UTC, Yu-Leo commented on uniqparser/uniqParser.go
> +package uniqparser
Названия файлов лучше писать в `snake_case`

2023-12-01 20:17 UTC, ch0c0-msk commented
> Это первичное (архитектурное) ревью; в тонкости решения решения пока не вникал.
> 
> Структура проекта очень близка к той, что мне хотелось бы видеть.
> 
> Я предлагаю следующий вариант разбиения на пакеты:
> 
> 1. Парсинг флагов и аргументов командной строки
> 2. "Бизнес-логика" - уникализация набора строк в зависимости от параметров
> 3. Чтение строк из stdin/файла
> 4. Запись строк в stdout/файл
> 5. main файл в корне репозитория, в котором "связываются" все пакеты
> 
> 3 и 4 пункты можно объединить в один пакет
> 
> Исправь структуру проекта в соответствии с этим разбиением (как сделаешь, напиши тут "ИСПРАВЛЕНО", чтобы я видел, что можно ещё раз посмотреть твое решение). После этого буду более детально смотреть, что можно поправить. На первый взгляд всё отлично)
> 
> P.S. За тесты респект!

ИСПРАВЛЕНО

2023-12-03 07:02 UTC, Yu-Leo requested changes
По структуре проекта - супер! Поправь эти замечания; как поправишь, так же напиши в комментах к MR-у, что поправил. После чего дам аппрув

2023-12-03 07:02 UTC, Yu-Leo commented on cmdutils/cmd_handler.go
> +	return result
Выглядит немного перегружено. Один из типовых вариантов упрощения таких конструкций - введение новых булеановских переменных:

```go
onlyC := opt.CFlag && !opt.DFlag && !opt.UFlag
onlyD := opt.DFlag && !opt.UFlag && !opt.CFlag
onlyU := opt.UFlag && !opt.DFlag && !opt.CFlag
noCDU := !opt.DFlag && !opt.UFlag && !opt.CFlag
positiveFS := (opt.FFlag >= 0) && (opt.SFlag >= 0)
return (onlyC || onlyD || onlyU || noCDU) && positiveFS
```

2023-12-03 07:02 UTC, Yu-Leo commented on fileutils/file_handler.go
> +	} else {
Не нужно писать всю основную логику в блок else. Если выполнится условие в if и затем return, то этот код и так не будет выполнен. Наглядно:

**Нет:**
```go
if a > b { // Особый случай
   return 123
} else {
    // Основная логика
   return result
}
```

**Да:**
```go
if a > b { // Особый случай
   return 123
}
// Основная логика
return result
```

Аналогично глянь везде по коду

2023-12-03 07:02 UTC, Yu-Leo commented on fileutils/file_handler.go
> +	}
Можно сократить до одной строчки
```go
return err
```

2023-12-03 07:02 UTC, Yu-Leo commented on uniqparser/uniq_parser_test.go
> +}
Думаю, лучше будет создать глобальную константу и испольльзовать её только в рамках этого пакета для тестирования:
```go
const testLines []string{"i love", "i love", "we love", "we love", "we ll love", "you love"}
```

2023-12-03 07:02 UTC, Yu-Leo commented on uniqparser/uniq_parser_test.go
> +}
Вместо использования этой функции (`opt := createEmptyOptions()`) можно писать `opt := &cmdutils.Options{}`. А ещё лучше - сразу создать экземпляр структуры с нужными значениями

2023-12-03 07:02 UTC, Yu-Leo commented on fileutils/file_handler.go
> +			}
Аналогично тому, что писал выше. Else не нужен:

```go
if err == io.EOF {
    break
}
return []string{}, err
```

2023-12-06 18:12 UTC, ch0c0-msk commented
> По структуре проекта - супер! Поправь эти замечания; как поправишь, так же напиши в комментах к MR-у, что поправил. После чего дам аппрув

ИСПРАВЛЕНО

2023-12-16 16:44 UTC, Yu-Leo approved these changes
**Аппрув! 🎆**

ДЗ принято.

Несколько небольших замечаний оставил, поправь и можешь смерджить ветки. Если будут какие-то вопросы, можешь прямо в этот PR написать

2023-12-16 16:44 UTC, Yu-Leo commented on fileutils/file_handler.go
> +
Лишняя пустая строка

2023-12-16 16:44 UTC, Yu-Leo commented on fileutils/file_handler.go
> +
Лишняя пустая строка

2023-12-16 16:44 UTC, Yu-Leo commented on uniqparser/uniq_parser.go
> +
Лишняя пустая строка

2023-12-16 16:44 UTC, Yu-Leo commented on uniqparser/uniq_parser_test.go
> +	"github.com/stretchr/testify/assert"
Импорты принято писать в таком порядке:
1. Дефолтные либы
2. Сторонние либы
3. Пакеты проекта

Между блоками пустые строки

2023-12-16 16:44 UTC, Yu-Leo commented on uniqparser/uniq_parser_test.go
> +}
Можно использовать table driven testing ([раз](https://go.dev/blog/subtests), [два](https://habr.com/ru/companies/otus/articles/741618/)), чтобы не плодить множество очень похожих тестовых функций

2023-12-24 17:58 UTC, ch0c0-msk commented
> **Аппрув! 🎆**
> 
> ДЗ принято.
> 
> Несколько небольших замечаний оставил, поправь и можешь смерджить ветки. Если будут какие-то вопросы, можешь прямо в этот PR написать

Все поправил. Можешь посмотреть, корректно ли сделал табличное тестирование?

2023-12-25 17:19 UTC, Yu-Leo commented
> Все поправил. Можешь посмотреть, корректно ли сделал табличное тестирование?

Да, супер. Можешь мерджить ветки

2023-12-25 21:11 UTC, merged